server:
  port: '8888'
spring:
  cloud:
    config:
      server:
        git:
          clone-on-start: 'true'
          uri: https://github.com/maritc23/configs.git
#          uri: file:/C:/datos/proyectoBanco/config-repo
